<?php

class Test_News_Model_Eavblogpost extends Mage_Core_Model_Abstract
{
    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('news-eav/blogpost');
    }
}